import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <head>
      <link rel="icon" href="assets/icons/logo.svg" type="image/svg+xml"/>

      </head>
        <body>
            <div className='login_background_overlay'>
                {children}

            </div>
            
        </body>

    </html>
  )
}
